// Code generated by entc, DO NOT EDIT.

package profile

const (
	// Label holds the string label denoting the profile type in the database.
	Label = "profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldGithubURL holds the string denoting the github_url field in the database.
	FieldGithubURL = "github_url"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldTwitterUsername holds the string denoting the twitter_username field in the database.
	FieldTwitterUsername = "twitter_username"
	// FieldPublicRepo holds the string denoting the public_repo field in the database.
	FieldPublicRepo = "public_repo"
	// FieldFollowers holds the string denoting the followers field in the database.
	FieldFollowers = "followers"
	// FieldFollowing holds the string denoting the following field in the database.
	FieldFollowing = "following"
	// FieldLastUpdated holds the string denoting the last_updated field in the database.
	FieldLastUpdated = "last_updated"
	// Table holds the table name of the profile in the database.
	Table = "profiles"
)

// Columns holds all SQL columns for profile fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAvatarURL,
	FieldGithubURL,
	FieldLocation,
	FieldBio,
	FieldTwitterUsername,
	FieldPublicRepo,
	FieldFollowers,
	FieldFollowing,
	FieldLastUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// GithubURLValidator is a validator for the "github_url" field. It is called by the builders before save.
	GithubURLValidator func(string) error
	// LocationValidator is a validator for the "location" field. It is called by the builders before save.
	LocationValidator func(string) error
	// FollowersValidator is a validator for the "followers" field. It is called by the builders before save.
	FollowersValidator func(int) error
	// FollowingValidator is a validator for the "following" field. It is called by the builders before save.
	FollowingValidator func(int) error
)
