// Code generated by entc, DO NOT EDIT.

package repo

const (
	// Label holds the string label denoting the repo type in the database.
	Label = "repo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRepoName holds the string denoting the repo_name field in the database.
	FieldRepoName = "repo_name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldLastUpdated holds the string denoting the last_updated field in the database.
	FieldLastUpdated = "last_updated"
	// Table holds the table name of the repo in the database.
	Table = "repos"
)

// Columns holds all SQL columns for repo fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRepoName,
	FieldURL,
	FieldDescription,
	FieldLanguage,
	FieldLastUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// RepoNameValidator is a validator for the "repo_name" field. It is called by the builders before save.
	RepoNameValidator func(string) error
)
