// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	Crabrave int    `json:"crabrave"`
}

type PostDto struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}
