// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PostDto struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type PostNode struct {
	Type string `json:"type"`
	Leaf string `json:"leaf"`
}
